@startuml TNT
skinparam groupInheritance 4
title 家园 这个demo暂时先不做物品,只制作功能
package "基本框架"
{
    class ArticleClass <<物品基类>>
    {
    {field}-name : string
    {field}-EArticleType : EArticleType
    {field}-optionalWorld : EWorld[]
    +{method}string GetName()
    }

    enum EArticleType<<物品类型>>
    {
        
    }
    enum EWorld<<世界>>
    {
        
    }


}
@enduml
